### ISSUE TITLE
Cannot search large files

### ISSUE THREAD

**Issue by hgardneriv** [ebeahan/log-collection#1]
Hello Eric,

I'm reviewing your submission and noticed it does not work with very large files, 1.5 GB in this case. Seeing a 500 error with ERR_STRING_TOO_LONG.

<img width="1738" alt="Screen Shot 2022-05-21 at 8 04 56 AM" src="https://user-images.githubusercontent.com/9706538/169652927-58e59d58-bac3-4856-8fdc-cc21888358d3.png">

Suggested approach to address the issue:
1. Open file
2. Seek to end
3. Read backwards chunk at a time until the requested number of events have been found.
4. Stream results as they are found
5. Don't provide option to return entire file (pick a reasonable max lines 5k).

Very nice job on the project, hopefully this makes sense.

**Comment by ebeahan** [comment]
Thanks for the feedback, @hgardneriv!

Changes introduced in #1 help to improve the handling of larger log files.
